kind: pipeline
type: docker
name: main

steps:
  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.10.0/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: proto
    image: golang:1.17
    commands:
      - make proto

---
kind: pipeline
type: docker
name: go
depends_on:
  - main

steps:
  - name: install
    image: golang:1.17
    commands:
      - make install
    volumes:
      - name: go_dependencies
        path: /go

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter
    volumes:
      - name: go_dependencies
        path: /go

  - name: test
    image: golang:1.17
    commands:
      - make test-coverage
    volumes:
      - name: go_dependencies
        path: /go

---
kind: pipeline
type: docker
name: js
depends_on:
  - main

steps:
  - name: install
    image: node:16
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - make install

  - name: npm
    image: plugins/npm
    settings:
      username: loeffel-io
      password:
        from_secret: NPM_PASSWORD
      email: lucas@loeffel.io
      folder: js
      access: public
    when:
      event: tag

volumes:
  - name: go_dependencies
    temp: { }