ls:
  .dir: snake_case
  .go: snake_case
  .js: snake_case
  .ts: snake_case
  .d.ts: snake_case
  .pb.go: snake_case
  .pb.extend.go: snake_case
  .pb.validate.go: snake_case

ignore:
  - .git
  - .idea